on:
  push:
    branches:
      - 'main'

name: Build code
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.0.0]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: tsc version
        run: 
          tsc -v
      - name: npm install and npm run build
        run: |
          cd game-applet
          npm i
          npm i -g firebase-tools
      - name: deploy to PRODUCTION !!
        run: |
          npm run bd-ci-cd-prod
